from dataclasses import dataclass
from typing import Dict, List, Tuple, cast

import numpy as np
import pandas as pd
from pandas import DataFrame, Series

from dataExtractor import BloombergData, PortfolioPosition


# ----- Results Classes ------
@dataclass
class PerformanceMetrics:
    total_return: float
    annualised_return: float
    annualised_vol: float
    sharpe: float
    sortino: float
    calmar: float
    max_drawdown: float
    max_drawdown_duration_days: int
    win_rate: float
    avg_win: float
    avg_loss: float
    gross_PL_ratio: float
    skewness: float
    kurtosis: float

    def summary(self) -> str: #Code completely generated by AI!
        lines = [
            "── Performance Metrics ─────────────────────────────",
            f"  Total Return        : {self.total_return:+.2%}",
            f"  Annualised Return   : {self.annualised_return:+.2%}",
            f"  Annualised Vol      : {self.annualised_vol:.2%}",
            f"  Sharpe Ratio        : {self.sharpe:.3f}",
            f"  Sortino Ratio       : {self.sortino:.3f}",
            f"  Calmar Ratio        : {self.calmar:.3f}",
            f"  Max Drawdown        : {self.max_drawdown:.2%}",
            f"  Max DD Duration     : {self.max_drawdown_duration_days}d",
            f"  Win Rate            : {self.win_rate:.1%}",
            f"  Avg Win / Avg Loss  : {self.avg_win:.2%} / {self.avg_loss:.2%}",
            f"  Gross P&L Ratio     : {self.gross_PL_ratio:.2f}",
            f"  Skewness / Kurtosis : {self.skewness:.2f} / {self.kurtosis:.2f}",
            "────────────────────────────────────────────────────",
        ]
        return "\n".join(lines)


@dataclass
class GreekSummary:
    delta: float
    gamma: float
    vega: float     # per 1% vol move
    theta: float    # per day
    rho: float      # per 1% rate move

    def summary(self) -> str: #Code completely generated by AI!
        lines = [
            "── Aggregated Greeks ────────────────────────────────",
            f"  Delta   : £{self.delta:+,.2f}",
            f"  Gamma   : £{self.gamma:+,.2f}",
            f"  Vega    : £{self.vega:+,.2f}  (per 1% Δvol)",
            f"  Theta   : £{self.theta:+,.2f}  (per day)",
            f"  Rho     : £{self.rho:+,.2f}  (per 1% Δrate)",
            "────────────────────────────────────────────────────",
        ]
        return "\n".join(lines)


# ── Portfolio Engine ──────────────────────────────────────────────────────────
class PortfolioEngine:
    """
    Evaluate a portfolio of positions against Bloomberg data.
    """

    def __init__(
        self,
        positions: List[PortfolioPosition],
        data: BloombergData,
        rf_annual: float = 0.02,
    ):
        self.positions = positions
        self.data = data
        self.rf = rf_annual
        self.rf_daily = (1 + rf_annual) ** (1 / 252) - 1

        # Map ticker → position(s)
        self.pos: Dict[str, List[PortfolioPosition]] = {}
        for p in positions:
            self.pos.setdefault(p.ticker, []).append(p)


    # ── Market values ─────────────────────────────────────────────────────
    def position_market_values(self) -> DataFrame:
        """Return DataFrame with cost basis, market value, unrealised P&L per position."""
        rows = []
        for pos in self.positions:
            price = self.data.last_prices[pos.ticker]
            mkt_val = pos.quantity * price * pos.multiplier
            cost = pos.quantity * pos.cost_basis * pos.multiplier
            pnl = mkt_val - cost
            rows.append({
                    "Ticker": pos.ticker,
                    "Asset Class": pos.asset_class,
                    "Quantity": pos.quantity,
                    "Cost Basis": pos.cost_basis,
                    "Last Price": price,
                    "Market Value (£)": mkt_val,
                    "Cost Value (£)": cost,
                    "Unrealised P&L (£)": pnl,
                    "Unrealised P&L (%)": pnl / abs(cost) if cost else np.nan,
                })
        df = DataFrame(rows)
        df.loc["TOTAL"] = {
            "Market Value (£)": df["Market Value (£)"].sum(),
            "Cost Value (£)": df["Cost Value (£)"].sum(),
            "Unrealised P&L (£)": df["Unrealised P&L (£)"].sum(),
        }
        return df

    @property
    def total_market_value(self) -> float:
        return sum(
            pos.quantity * self.data.last_prices[pos.ticker] * pos.multiplier
            for pos in self.positions
        )

    @property
    def weights(self) -> Series:
        """Market-value weights per ticker."""
        vals: Dict[str, float] = {}
        for pos in self.positions:
            price = self.data.last_prices[pos.ticker]
            mv = pos.quantity * price * pos.multiplier
            vals[pos.ticker] = vals.get(pos.ticker, 0) + mv
        s = Series(vals)
        return s / s.sum()

    # ── Portfolio returns ─────
    def portfolio_returns(self) -> Series:
        """Weighted log-return series of the portfolio."""
        w = self.weights
        common = self.data.returns.columns.intersection(w.index)
        return (self.data.returns[common] @ w[common]).rename("Portfolio")

    def cumulative_returns(self) -> Series:
        return (1 + self.portfolio_returns()).cumprod() - 1

    # ── Drawdown ─────
    @staticmethod
    def _compute_drawdown(cum_rets: Series) -> Tuple[float, int]:
        """Return (max_drawdown, max_duration_days)"""
        wealth = 1 + cum_rets
        peak = wealth.cummax()
        dd = (wealth - peak) / peak
        max_dd = float(dd.min())

        # Duration
        in_dd = dd < 0
        max_dur = 0
        cur = 0
        for val in in_dd:
            if val:
                cur += 1
                max_dur = max(max_dur, cur)
            else:
                cur = 0

        return max_dd, max_dur

    # ── Performance metrics object returning all key stats ─────
    def performance_metrics(self) -> PerformanceMetrics:
        rets = self.portfolio_returns()
        cum = self.cumulative_returns()
        n = len(rets)

        total_ret = float(cum.iloc[-1])
        ann_ret = float((1 + total_ret) ** (252 / n) - 1)
        ann_vol = float(rets.std() * np.sqrt(252))

        excess = rets - self.rf_daily
        sharpe = float(excess.mean() / rets.std() * np.sqrt(252)) if rets.std() > 0 else 0.0

        downside = rets[rets < self.rf_daily]
        downside_std = float(downside.std() * np.sqrt(252)) if len(downside) > 1 else 1e-9
        sortino = float((ann_ret - self.rf) / downside_std)

        max_dd, max_dd_dur = self._compute_drawdown(cum)
        calmar = float(ann_ret / abs(max_dd)) if max_dd != 0 else np.inf

        wins = rets[rets > 0]
        losses = rets[rets < 0]
        win_rate = float(len(wins) / n)
        avg_win = float(wins.mean()) if len(wins) else 0.0
        avg_loss = float(losses.mean()) if len(losses) else 0.0
        profit_factor = (
            float(wins.sum() / abs(losses.sum()))
            if losses.sum() != 0
            else np.inf
        )

        return PerformanceMetrics(
            total_return=total_ret,
            annualised_return=ann_ret,
            annualised_vol=ann_vol,
            sharpe=sharpe,
            sortino=sortino,
            calmar=calmar,
            max_drawdown=max_dd,
            max_drawdown_duration_days=max_dd_dur,
            win_rate=win_rate,
            avg_win=avg_win,
            avg_loss=avg_loss,
            gross_PL_ratio=profit_factor,
            skewness=float(cast(float, rets.skew())),
            kurtosis=float(cast(float, rets.kurt())),
        )

    # ── Rolling metrics ───────────────────────────────────────────────────
    def rolling_metrics(self, window: int = 63) -> DataFrame:
        """Rolling Sharpe, vol, and return over `window` trading days."""

        rets = self.portfolio_returns()
        rf_d = self.rf_daily
        roll = DataFrame(index=rets.index)
        roll["Rolling Return (ann.)"] = rets.rolling(window).mean() * 252
        roll["Rolling Vol (ann.)"] = rets.rolling(window).std() * np.sqrt(252)
        roll["Rolling Sharpe"] = (
            (rets - rf_d).rolling(window).mean()
            / rets.rolling(window).std()
            * np.sqrt(252)
        )

        return roll.dropna()

    # ── Greeks aggregation ────────────────────────────────────────────────
    def aggregated_greeks(self) -> GreekSummary:
        """
        Aggregate position-level greeks into portfolio-level sensitivities.
        For equities: delta = 1 (per share), all higher-order greeks = 0.
        For options: use Bloomberg greek fields (could use bsmFuncs too)
        """
        
        total: Dict[str, float] = dict(delta=0.0, gamma=0.0, vega=0.0, theta=0.0, rho=0.0)
        g = self.data.greeks

        for pos in self.positions:
            price = float(self.data.last_prices[pos.ticker])
            qty = pos.quantity * pos.multiplier

            if pos.asset_class == "Equity":
                # Equity: delta = 1 per share in price units
                total["delta"] += qty * price * 1.0 #type: ignore
            elif pos.asset_class == "Option" and pos.ticker in g.index:
                row = g.loc[pos.ticker]
                total["delta"] += qty * price * row.get("DELTA_MID", 0) #type: ignore
                total["gamma"] += qty * price * row.get("GAMMA_MID", 0) #type: ignore
                total["vega"] += qty * row.get("VEGA_MID", 0) * 100  # per 1% #type: ignore
                total["theta"] += qty * row.get("THETA_MID", 0) #type: ignore
                total["rho"] += qty * row.get("RHO_MID", 0) * 100    # per 1% #type: ignore

        return GreekSummary(**total)

    # ── Sector / ticker concentration ────────
    def concentration(self) -> DataFrame:
        w = self.weights.sort_values(ascending=False)
        df = w.rename("Weight").to_frame()
        df["Weight (%)"] = (df["Weight"] * 100).map("{:.2f}%".format)
        
        # Herfindahl-Hirschman Index
        hhi = float((w**2).sum())
        df.attrs["HHI"] = hhi
        df.attrs["Effective_N"] = 1 / hhi

        return df

    # ── Full print report ───────
    def printOutput(self): #Code completely generated by AI!
        print("\n" + "═" * 52)
        print("  PORTFOLIO ANALYTICS REPORT")
        print("═" * 52)

        mv = self.position_market_values()
        print("\n── Positions ─────────────────────────────────────────")
        print(
            mv[["Ticker", "Asset Class", "Market Value (£)", "Unrealised P&L (£)", "Unrealised P&L (%)"]].to_string(index=False)
        )

        pm = self.performance_metrics()
        print("\n" + pm.summary())

        gs = self.aggregated_greeks()
        print(gs.summary())

        conc = self.concentration()
        hhi = conc.attrs.get("HHI", np.nan)
        eff_n = conc.attrs.get("Effective_N", np.nan)
        print("── Concentration ────────────────────────────────────")
        print(conc[["Weight (%)"]].to_string())
        print(f"  HHI: {hhi:.4f}  |  Effective N: {eff_n:.1f}")
        print("────────────────────────────────────────────────────")
